# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]


modId="${mod_id}"

version="${mod_version}"
displayName="${mod_name}"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
#credits="" #optional

# A text field displayed in the mod UI
authors="${mod_authors}" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    type="required"
    # Optional field describing why the dependency is required or why it is incompatible
    # reason="..."
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="required"
versionRange="[${ae2_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="soulplied_energistics"
type="required"
versionRange="[${soulplied_energistics_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="industrialforegoing"
type="required"
versionRange="[${industrial_foregoing_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="industrialforegoingsouls"
type="required"
versionRange="[${industrial_foregoing_souls_mod_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="titanium"
type="required"
versionRange="[${titanium_mod_version},)"
ordering="NONE"
side="BOTH"


# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
